project/website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Closet(db.Model):
    __tablename__= 'closet'
    id = db.Column(db.Integer, primary_key=True)
    closet_name = db.Column(db.String(200), nullable=False)
    items = db.relationship('Item', backref='closet', lazy=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user_info.id'))

    def addCloset(self): #adds closet to user
        User.closets.append(self)

class Item(db.Model):
    __tablename__= 'item'
    id = db.Column(db.Integer, primary_key=True)
    category = db.Column(db.String(50))
    color = db.Column(db.String(50))
    season = db.Column(db.String(50))
    style = db.Column(db.String(50))
    fit = db.Column(db.String(50))
    closet_id = db.Column(db.Integer, db.ForeignKey('closet.id'))

   # def addItem(self): #adds item to closet
   #     Closet.items.append(self)

class User(db.Model, UserMixin):
    __tablename__= 'user_info'
    id = db.Column(db.Integer, primary_key=True)
    firstName = db.Column(db.String(100))
    lastName = db.Column(db.String(100))
    userName = db.Column(db.String(30), unique=True)
    password = db.Column(db.String(15))
    closets = db.relationship('Closet')



    


project/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask import current_app
import os
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'extremelysecretkey'
    app.config['SQLALCHEMY_DATABASE_URI'] =f'sqlite:///{DB_NAME}'

    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    from .models import User, Closet, Item
    
    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))     
    
    #print_table(db, 'item')

    return app

def print_table(db, table_name):
    engine = db.create_engine('sqlite:///database.db')
    connection = engine.connect()
    metadata = db.MetaData()
    table_info = db.Table(table_name, metadata, autoload=True, autoload_with=engine)

    print(table_info.columns.keys())
    print(repr(metadata.tables[table_name]))

def create_database(app):
    with app.app_context():
        if not path.exists('website/' + DB_NAME):
            db.create_all()
            print('Created Database!')

        #abs_path = os.path.abspath("website/" + DB_NAME)
        #print("Database path:", abs_path)




project/website/auth.py
from flask import Blueprint, request, get_flashed_messages, render_template, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == 'POST':
        userName = request.form.get('userName')
        password = request.form.get('password')

        user_exists = User.query.filter_by(userName=userName).scalar() is not None

        print("user:", user_exists)

        if user_exists:
            user = User.query.filter_by(userName=userName).first()
            if check_password_hash(user.password, password):
                print('logged in successfully')
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password; try again!', category='error')
        else:
            flash('Email does not exist. Sign up?', category='error')

    return render_template("loginwcss.html", user=current_user)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == 'POST':
        firstName = request.form.get('firstName')
        lastName = request.form.get('lastName')
        userName = request.form.get('userName')
        password1 = request.form.get('pwd1')
        password2 = request.form.get('pwd2')

        user = User.query.filter_by(userName=userName).first()
        
        if user:
            flash('This username already exists.', category='error')
            print(userName, 'username already exists')
        elif userName is None or len(userName) < 5:
            flash('Username must be at least 4 characters.', category='error')
        elif len(firstName) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords do not match.', category='error')
        elif len(password1) < 3:
            flash('Password must be at least 5 characters', category='error')
        else:
            new_user = User(firstName=firstName, lastName=lastName, userName=userName, 
                            password=generate_password_hash(password1, method='sha256') )
            db.session.add(new_user)
            db.session.commit()
            
            login_user(user, remember=True)

            #flash('Account successfully created!', category='success')
            print('Account created')
            return redirect(url_for('views.home'))
        
    return render_template("signupwcss.html", user=current_user)

project/website/views.py
from flask import Flask, Blueprint, redirect, request, render_template, url_for, flash
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from flask_login import login_required, current_user
from . import db
from .models import User, Closet, Item

views = Blueprint('views', __name__)

@views.route("/")
@login_required
def home():
    return render_template("indexwcss.html", user=current_user)

@views.route("/dashboard")
@login_required
def dashboard():
    users = User.query.all()

    for person in users:
        print(person.firstName)
        print(person.lastName)

    print(users)

    items = Item.query.all()

    for thing in items:
        print(thing.color)


    return render_template("dashboardwcss.html", user=current_user)

@views.route("/closet")
@login_required
def closet():
    #display items

    return render_template("closetwcss.html", user=current_user)

@views.route("/addItem", methods=['GET', 'POST'])
@login_required
def addItem():
    if request.method == 'POST':
        category = request.form.get('addCategory')
        color = request.form.get('addColor')
        style = request.form.get('addStyle')
        season = request.form.get('addSeason')
        fit = request.form.get('addFit')

        new_item = Item(category=category, color=color, style=style, season=season, fit=fit, ) #creates new item
        print("item added")
        print(new_item.color)

        db.session.add(new_item) #adds new item to database
        db.session.commit()

    return render_template("additemwcss.html", user=current_user)

@views.route("/create-new-closet", methods=['GET', 'POST'])
@login_required
def addCloset():
    if request.method == 'POST':
        name = request.form.get('closetName')

        new_closet = Closet(closet_name=name, user_id=current_user.id)

        db.session.add(new_closet)
        db.session.commit()

        print(new_closet.closet_name)
    return render_template("createcloset.html", user=current_user)

project/website/templates/additemwcss.html
  {% extends "base.html" %}

  {% block title %}Closet{% endblock %}
  
  {% block content %}
  <!-- Header -->
  <div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-jumbo"><b>Create a New Item</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
  </div>

    <div class="b">
      <ul class="w3-ul w3-light-grey w3-center">
      <form id="form" class="newForm" method='POST' action="{{url_for('views.addItem')}}">
        <li class="w3-black w3-xlarge w3-padding-32">
            <div class="w3-row-padding">
              <div class="w3-half">
                 <input type="file" id="image_input" accept="image/png, image/jpg, image/heif, image/heic, image/heif">
              </div>
            </div>
        </li>
            <div id="descriptors">
                <div class="c">
                  <li class="w3-padding-15">
                  <label for="addCategory">Category:</label>
                  <select name="addCategory" id="addCategory">
                        <option value="select">Select</option>
                    <optgroup label="Top">
                        <option value="tshirt">T-Shirt</option>
                        <option value="longsleeve">Long Sleeve Shirt</option>
                        <option value="crewneck">Crewneck</option>
                        <option value="buttondown">Button-Down</option>
                        <option value="cropped">Cropped</option>
                        <option value="tanktop">Tank-Top</option>
                        <option value="turtleneck">Turtleneck</option>
                        <option value="blouse">Blouse</option>
                    </optgroup>
                    <optgroup label="Dresses">
                        <option value="maxi">Maxi</option>
                        <option value="midi">Midi</option>
                        <option value="midlength">Mid-Length</option>
                        <option value="mini">Mini</option>
                    </optgroup>
                    <optgroup label="Bottom">
                        <option value="jeans">Jeans</option>
                        <option value="cargo">Cargo Pants</option>
                        <option value="sweats">Sweatpants</option>
                        <option value="leggings">Leggings</option>
                        <option value="skirts">Skirts</option>
                        <option value="slacks">Slacks</option>
                        <option value="pants">Pants</option>
                        <option value="other">Other</option>
                    </optgroup>
                    <optgroup label="Shoes">
                        <option value="sneakers">Sneakers</option>
                        <option value="sandals">Sandals</option>
                        <option value="boots">Boots</option>
                        <option value="heels">Heels</option>
                        <option value="dressshoes">Dress Shoes</option>
                    </optgroup>
                    <optgroup label="Outerwear">
                        <option value="jacket">Jacket</option>
                        <option value="cardigan">Cardigan</option>
                        <option value="blazer">Blazer</option>
                        <option value="hoodie">Hoodie</option>
                    </optgroup>
                    <optgroup label="Accessories">
                        <option value="hats">Hats</option>
                        <option value="glasses">Glasses</option>
                        <option value="scarves">Scarves</option>
                        <option value="jewelry">Jewelry</option>
                        <option value="bags">Bags</option>
                        <option value="belts">Belts</option>
                    </optgroup>
                  </select>
                  
                  <li class="w3-padding-15">
                  <label for="addColor">Color:</label>
                  <select name="addColor" id="addColor">
                    <option value="select">Select</option>
                    <option value="black">Black</option>
                    <option value="white">White</option>
                    <option value="gray">Gray</option>
                    <option value="brown">Brown</option>
                    <option value="beige">Beige</option>
                    <option value="Red">Red</option>
                    <option value="orange">Orange</option>
                    <option value="yellow">Yellow</option>
                    <option value="green">Green</option>
                    <option value="teal">Teal</option>
                    <option value="blue">Blue</option>
                    <option value="purple">Purple</option>
                    <option value="pink">Pink</option>
                    <option value="gold">Gold</option>
                    <option value="silver">Silver</option>
                    <option value="multicolor">Multi-Color</option>  
                  </select>
                  <li class="w3-padding-15">
                  <label for="addStyle">Style:</label>
                  <select name="addStyle" id="addStyle">
                    <option value="select">Select</option>
                    <option value="alternative">Alternative</option>
                    <option value="athleisure">Athleisure</option>
                    <option value="bohemian">Bohemian</option>
                    <option value="businesscasual">Business Casual</option>
                    <option value="businessprofessional">Business Professional</option>
                    <option value="chic">Chic</option>
                    <option value="ethnic">Ethnic</option>
                    <option value="feminine">Feminine</option>
                    <option value="formal">Formal</option>
                    <option value="gothic">Gothic</option>
                    <option value="grunge">Grunge</option>
                    <option value="masculine">Masculine</option>
                    <option value="minimalist">Minimalist</option>
                    <option value="preppy">Preppy</option>
                    <option value="semiformal">Semi-Formal</option>
                    <option value="streetwear">Streetwear</option> 
                    <option value="trendy">Trendy</option> 
                    <option value="vintage">Vintage</option> 
                    <option value="other">Other</option> 
                  </select>
                  <li class="w3-padding-15">
                  <label for="addSeason">Season:</label>
                  <select name="addSeason" id="addSeason">
                    <option value="select">Select</option>
                    <option value="winter">Winter</option>
                    <option value="spring">Spring</option>
                    <option value="summer">Summer</option>
                    <option value="autumn">Autumn</option>
                    <option value="any">Any</option>
                  </select>
                  <li class="w3-padding-15">
                  <label for="addFit">Fit:</label>
                  <select name="addFit" id="addFit">
                    <option value="select">Select</option>
                    <option value="loose">Loose</option>
                    <option value="regular">Regular</option>
                    <option value="tight">Tight</option>
                  </select>
                  <li class="w3-padding-15">
                </div>
        <button type="submit" id="btn">Add Item</button>
      </form>
      <div id="showCloset"></div>
      <!--script src="inputscript.js"></script>
        <li class="w3-light-grey w3-padding-15"></li>
      </ul-->
    </div>

  <!-- Modal for full size images on click-->
  <div id="modal01" class="w3-modal w3-black" style="padding-top:0" onclick="this.style.display='none'">
    <span class="w3-button w3-black w3-xxlarge w3-display-topright">×</span>
    <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
      <img id="img01" class="w3-image">
      <p id="caption"></p>
    </div>
  </div>

  <script>
    // Modal Image Gallery
    function onClick(element) {
      document.getElementById("img01").src = element.src;
      document.getElementById("modal01").style.display = "block";
      var captionText = document.getElementById("caption");
      captionText.innerHTML = element.alt;
    }
  </script>
{% endblock %}
<!-- End page content -->
</div>

<script>
// Accordion 
function myAccFunc() {
  var x = document.getElementById("demoAcc");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// Click on the "Jeans" link on page load to open the accordion for demo purposes
document.getElementById("myBtn").click();


// Open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}


</script>

</body>
</html>

project/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}CloSets{% endblock %}</title>

    <meta charset="UTF-8">

    <!-- This gives us the main structure -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    .w3-sidebar a {font-family: "Roboto", sans-serif}
    body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
    </style>
  </head>
  <body class="w3-content" style="max-width:1200px">
    <!-- Sidebar/menu -->
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
          {% if category == 'error' %}
          <div class="alert alert-{{ category }} alert-dismissable fade show" role="alert">
              <li>{{ message }}</li>
              <button type="button" class="closebtn" data-dismiss="alert"
                  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
          </div>
          {% else %}
          <div class="alert alert-{{ category }} alert-dismissable fade show" role="alert">
              <li>{{ message }}<li>
              <button type="button" class="closebtn" data-dismiss="alert"
                  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
          </div>
          {% endif %}
          {% endfor %}
      {% endif %}
    {% endwith %}
    
    {% if user.is_authenticated %}
    <nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:3;width:250px" id="mySidebar">
      <div class="w3-container w3-display-container w3-padding-16">
        <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
        <h3><a href="/" class="w3-wide w3-bar-item w3-button w3-padding-top-48 w3-hover-white w3-display-topleft"><b>CloSets</b></a></h3>
      </div>
      <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">
        <a href="/dashboard" class="w3-bar-item w3-button">Dashboard</a>
        <a href="/closet" class="w3-bar-item w3-button">My Closet</a>
        <a href="/create-new-closet" class="w3-bar-item w3-button">Create New Closet</a>
        <a onclick="myAccFunc()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" id="myBtn">
          Subclosets <i class="fa fa-caret-down"></i>
        </a>
        <div id="demoAcc" class="w3-bar-block w3-hide w3-padding-large w3-medium">
          <a href="#" class="w3-bar-item w3-button w3-light-grey"><i class="fa fa-caret-right w3-margin-right"></i>Subcloset 1</a>
          <a href="#" class="w3-bar-item w3-button">Subcloset 2</a>
          <a href="#" class="w3-bar-item w3-button">Subcloset 3</a>
          <a href="#" class="w3-bar-item w3-button">Subcloset 4</a>
        </div>
      </div>
    </nav>
    {% endif %}

    <!-- Top menu on small screens -->
    <header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
      <h3><a href="/" class="w3-bar-item w3-padding-24 w3-wide"><b>CloSets</b></a></h3>
      <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
      <a href="/login" class="w3-bar-item w3-padding-24 w3-wide">Login</a>
      <a href="/logout" class="w3-bar-item w3-padding-24 w3-wide">Log Out</a>
      <a href="/signup" class="w3-bar-item w3-padding-24 w3-wide">Sign Up</a>
    </header>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- !PAGE CONTENT! -->
    <div class="w3-main" style="margin-left:250px">

      <!-- Push down content on small screens -->
      <div class="w3-hide-large" style="margin-top:83px"></div>
      
      
      <!-- Top header -->
      <header class="w3-container w3-xlarge">
        <p class="w3-right">
          {% if user.is_authenticated %}
          <a href="/logout" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Log Out</a>
          {% else %}
          <a href="/login" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Login</a>
          <a href="/signup" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white">Sign Up</a>
          {% endif %}
        </p>
      </header>

      {% block content %}
        
      {% endblock %}


      <!-- End page content -->
    </div>


    <script>
    // Accordion 
    function myAccFunc() {
      var x = document.getElementById("demoAcc");
      if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
      } else {
        x.className = x.className.replace(" w3-show", "");
      }
    }

    document.getElementById("myBtn").click();


    // Open and close sidebar
    function w3_open() {
      document.getElementById("mySidebar").style.display = "block";
      document.getElementById("myOverlay").style.display = "block";
    }
    
    function w3_close() {
      document.getElementById("mySidebar").style.display = "none";
      document.getElementById("myOverlay").style.display = "none";
    }

    </script>

  </body>
</html>

project/website/templates/closetwcss.html
  {% extends "base.html" %}

  {% block title %}Closet{% endblock %}
  
  {% block content %}
  <div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-jumbo"><b>Closet Name</b></h1>
    <a href='/addItem' class="w3-xlarge w3-text-black"><b>New Item</b></a><br>
    <a href='/addOutfit' class="w3-xlarge w3-text-black"><b>New Outfit</b></a>
    <hr style="width:50px;border:5px solid red" class="w3-round">
  </div>
  

  <!-- Modal for full size images on click-->
  <div id="modal01" class="w3-modal w3-black" style="padding-top:0" onclick="this.style.display='none'">
    <span class="w3-button w3-black w3-xxlarge w3-display-topright">×</span>
    <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
      <img id="img01" class="w3-image">
      <p id="caption"></p>
    </div>
  </div>

  <script>
    // Modal Image Gallery
    function onClick(element) {
      document.getElementById("img01").src = element.src;
      document.getElementById("modal01").style.display = "block";
      var captionText = document.getElementById("caption");
      captionText.innerHTML = element.alt;
    }
  </script>
  {% endblock %}

project/website/templates/createcloset.html
{% extends "base.html" %}

{% block title %}Closet{% endblock %}

{% block content %}
<div class="w3-container" style="margin-top:80px" id="showcase">
  <h1 class="w3-jumbo"><b>Create a New Closet</b></h1>
    <a href='/addItem' class="w3-xlarge w3-text-black"><b>New Item</b></a><br>
    <a href='/addOutfit' class="w3-xlarge w3-text-black"><b>New Outfit</b></a>
  <hr style="width:50px;border:5px solid red" class="w3-round">
  <div>
    <form id="form" class="newForm" method='POST' action="{{url_for('views.addCloset')}}">
        <label for="closetName" class="w3-xlarge w3-text-black"><b>Closet Name: </b></label>
        <input type="text" placeholder="Enter Closet Name" name="closetName" id="closetName"required>
        <button type="submit" class="signupbtn">Submit</button>
    </form>
  </div>
</div>



<!-- Modal for full size images on click-->
<div id="modal01" class="w3-modal w3-black" style="padding-top:0" onclick="this.style.display='none'">
  <span class="w3-button w3-black w3-xxlarge w3-display-topright">×</span>
  <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
    <img id="img01" class="w3-image">
    <p id="caption"></p>
  </div>
</div>

<script>
  // Modal Image Gallery
  function onClick(element) {
    document.getElementById("img01").src = element.src;
    document.getElementById("modal01").style.display = "block";
    var captionText = document.getElementById("caption");
    captionText.innerHTML = element.alt;
  }
</script>
{% endblock %}

project/website/templates/dashboardwcss.html
  {% extends "base.html" %}
  {% block title %}Dashboard{% endblock %}

  {% block content %}
  <div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-jumbo"><b>Dashboard</b></h1>
    <hr style="width:50px;border:5px solid red" class="w3-round">
  </div>
  
  

  <!-- Modal for full size images on click-->
  <div id="modal01" class="w3-modal w3-black" style="padding-top:0" onclick="this.style.display='none'">
    <span class="w3-button w3-black w3-xxlarge w3-display-topright">×</span>
    <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
      <img id="img01" class="w3-image">
      <p id="caption"></p>
    </div>
  </div>

  <script>
    // Modal Image Gallery
    function onClick(element) {
      document.getElementById("img01").src = element.src;
      document.getElementById("modal01").style.display = "block";
      var captionText = document.getElementById("caption");
      captionText.innerHTML = element.alt;
    }
  </script>
  {% endblock %}

project/website/templates/indexwcss.html
{% extends "base.html" %}

{% block title %}Homepage{% endblock %}

{% block content %}
  <!-- Image header -->
  <div class="w3-display-container w3-container">
    <!--img src="/w3images/jeans.jpg" alt="Jeans" style="width:100%"-->
        <div class="w3-display-topleft w3-text-black" style="padding:24px 48px">
        <h1 class="w3-jumbo w3-hide-small">CloSets</h1>
        <h1 class="w3-hide-large w3-hide-medium">CloSets</h1>
        <h1 class="w3-hide-small">Fashion, functionality, and flexibility, right at your fingertips!</h1>
        </div>
    </div>
{% endblock %}

project/website/templates/signupwcss.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <head>

    <style>
    body {font-family: Arial, Helvetica, sans-serif;}
    * {box-sizing: border-box}

    /* Full-width input fields */
    input[type=text], input[type=password] {
      width: 100%;
      padding: 15px;
      margin: 5px 0 22px 0;
      display: inline-block;
      border: none;
      background: #f1f1f1;
    }

    input[type=text]:focus, input[type=password]:focus {
      background-color: #ddd;
      outline: none;
    }

    hr {
      border: 1px solid #f1f1f1;
      margin-bottom: 25px;
    }

    /* Set a style for all buttons */
    button {
      background-color: #04AA6D;
      color: white;
      padding: 14px 20px;
      margin: 8px 0;
      border: none;
      cursor: pointer;
      width: 100%;
      opacity: 0.9;
    }

    button:hover {
      opacity:1;
    }

    /* Extra styles for the cancel button */
    .cancelbtn {
      padding: 14px 20px;
      background-color: #f44336;
    }

    /* Float cancel and signup buttons and add an equal width */
    .cancelbtn, .signupbtn {
      float: left;
      width: 50%;
    }

    /* Add padding to container elements */
    .container {
      padding: 16px;
    }

    /* Clear floats */
    .clearfix::after {
      content: "";
      clear: both;
      display: table;
    }

    /* Change styles for cancel button and signup button on extra small screens */
    @media screen and (max-width: 300px) {
      .cancelbtn, .signupbtn {
        width: 100%;
      }
    }
    </style>
  </head>

  <body>
    <form style="border:1px solid #ccc" method="POST" action="{{url_for('auth.signup')}}">
      <div class="container">
        <h1>Sign Up</h1>
        <hr>

        <label for="firstName"><b>First Name</b></label>
        <input type="text" placeholder="Enter First Name" name="firstName" id="firstName"required>

        <label for="lastName"><b>Last Name</b></label>
        <input type="text" placeholder="Enter Last Name" name="lastName" id="lastName" required>

        <label for="userName"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="userName" id="userName" required>

        <label for="pwd1"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="pwd1" id="pwd1" required>

        <label for="pwd2"><b>Confirm Password</b></label>
        <input type="password" placeholder="Confirm Password" name="pwd2" id="pwd2" required>
        
        <label>
          <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
        </label>
        
        <div class="clearfix">
          <button type="button" class="cancelbtn">Cancel</button>
          <button type="submit" class="signupbtn">Sign Up</button>
        </div>
          <span class="psw">Already have an account? <a href="#" onclick="window.location.href='login'">Log In Here</a> </span>

      </div>
    </form>

  </body>
{% endblock %}